#!/usr/bin/env bash

set -e
set -o pipefail

if [[ "${CI_TARGET}" == lint ]]; then
  exit
fi

mkdir "${BUILD_DIR}"
cd "${BUILD_DIR}"
echo "cmake ${CMAKE_FLAGS} .."
cmake "${CMAKE_FLAGS}" ..

echo "cmake -DENABLE_OPENMP=FALSE -DENABLE_COVERAGE=FALSE -DENABLE_EXAMPLES=FALSE -DENABLE_METAMODEL=TRUE -DENABLE_OPTIMIZE=TRUE -DENABLE_ARPACK=TRUE -DENABLE_GEOMETRYCONCRETE=TRUE -DENABLE_MPI=TRUE -DCMAKE_BUILD_TYPE=Release -DENABLE_EXAMPLES=TRUE .."
cmake -DENABLE_OPENMP=FALSE -DENABLE_COVERAGE=FALSE -DENABLE_EXAMPLES=FALSE -DENABLE_METAMODEL=TRUE -DENABLE_OPTIMIZE=TRUE -DENABLE_ARPACK=TRUE -DENABLE_GEOMETRYCONCRETE=TRUE -DENABLE_MPI=TRUE -DCMAKE_BUILD_TYPE=Release -DENABLE_EXAMPLES=TRUE ..
